'use client'

import { useEffect, useState } from "react"
import Image from "next/image"
import Link from "next/link"

interface Manga { mal_id:number; title:string; images:{jpg:{large_image_url:string}}; rank?:number; genres?:{name:string}[] }
interface CartItem { id:number; title:string; image:string; price:number; quantity:number }
const slug=(title:string)=>title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")
const price=(id:number)=>[5.99,7.49,9.99,12.99,14.99][id%5]

export default function FavoritesPage(){
 const [favorites,setFavorites]=useState<number[]>([]),[items,setItems]=useState<Manga[]>([]),[loading,setLoading]=useState(true)
 useEffect(()=>{try{setFavorites(JSON.parse(localStorage.getItem("favorites")||"[]"))}catch{};fetch("/api/manga").then(r=>r.json()).then(d=>setItems(Array.isArray(d.data)?d.data:[])).catch(console.error).finally(()=>setLoading(false))},[])
 const remove=(id:number)=>{const next=favorites.filter(x=>x!==id);setFavorites(next);localStorage.setItem("favorites",JSON.stringify(next))}
 const addToCart=(m:Manga)=>{const p=price(m.mal_id);const cart:CartItem[]=JSON.parse(localStorage.getItem("cart")||"[]");const found=cart.find(x=>x.id===m.mal_id);if(found)found.quantity++;else cart.push({id:m.mal_id,title:m.title,image:m.images?.jpg?.large_image_url||"",price:p,quantity:1});localStorage.setItem("cart",JSON.stringify(cart))}
 const selected=items.filter(m=>favorites.includes(m.mal_id))
 if(loading)return <main className="kami-paper-texture min-h-screen flex items-center justify-center"><div className="text-center"><span className="kami-vertical text-xs tracking-[.4em] text-[var(--kami-red)]">KAMI</span><p className="mt-5 text-[10px] uppercase tracking-[.3em] text-[var(--kami-muted)]">Chargement de la collection</p></div></main>
 return <main className="kami-paper-texture min-h-screen"><section className="max-w-7xl mx-auto px-5 md:px-10 lg:px-16 pt-12 md:pt-20 pb-12"><div className="border-b kami-line pb-5 flex items-end justify-between"><div><p className="text-[9px] uppercase tracking-[.4em] text-[var(--kami-red)]">Bibliothèque / 08</p><h1 className="kami-display text-6xl md:text-8xl mt-3">Favoris</h1></div><span className="kami-vertical hidden md:block text-[10px] tracking-[.35em] text-[var(--kami-muted)]">お気に入り</span></div><p className="mt-6 text-sm text-[var(--kami-muted)]">{selected.length} œuvre{selected.length>1?"s":""} conservée{selected.length>1?"s":""} dans votre bibliothèque.</p></section>{selected.length===0?<section className="max-w-3xl mx-auto px-5 py-16 text-center border-y kami-line"><p className="kami-vertical mx-auto text-[10px] tracking-[.35em] text-[var(--kami-red)] h-20">まだない</p><h2 className="kami-display text-4xl md:text-5xl mt-4">Votre bibliothèque est vide</h2><p className="mt-4 text-sm leading-6 text-[var(--kami-muted)]">Explorez la collection et marquez vos prochaines lectures.</p><Link href="/tri" className="kami-link inline-block mt-8 text-[10px] uppercase tracking-[.25em]">Explorer les mangas →</Link></section>:<section className="max-w-7xl mx-auto px-5 md:px-10 lg:px-16 pb-20"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-x-4 md:gap-x-6 gap-y-10">{selected.map((m,i)=><article key={m.mal_id} className="group"><div className="relative aspect-[3/4] overflow-hidden border kami-line bg-[var(--kami-paper-strong)]"><Link href={`/card/${slug(m.title)}`}><Image src={m.images?.jpg?.large_image_url||"/placeholder.svg"} alt={m.title} fill className="object-cover transition duration-700 group-hover:scale-[1.04]" /></Link><button onClick={()=>remove(m.mal_id)} className="absolute right-3 top-3 bg-[var(--kami-paper)]/90 border kami-line px-3 py-2 text-[9px] uppercase tracking-[.15em]" aria-label="Retirer des favoris">Retirer</button></div><h3 className="kami-display text-xl mt-3 leading-tight">{m.title}</h3><div className="flex items-center justify-between mt-2"><span className="text-[8px] uppercase tracking-[.2em] text-[var(--kami-muted)]">{m.genres?.[0]?.name||"Manga"} · {price(m.mal_id).toFixed(2)} €</span><button onClick={()=>addToCart(m)} className="kami-link text-[8px] uppercase tracking-[.18em]">Panier +</button></div></article>)}</div><div className="mt-16 border-t kami-line pt-5 text-right"><Link href="/tri" className="kami-link text-[9px] uppercase tracking-[.25em]">Continuer la découverte →</Link></div></section>}</main>
}
